lukeblog/lukeblog/urls.py
# --- 库 ---
from django.urls import path, include
from django.contrib import admin
# import xadmin
# from xadmin.plugins import xversion  # version模块自动注册需要版本控制的 Model
import mgadmin
from mgadmin.plugins import xversion
from django.contrib.sitemaps import views as sitemap_views
from django.views.decorators.cache import cache_page  # Django的缓存模块

# 配置文件上传及访问路径(生产环境用Nginx完成)
from django.conf import settings
from django.conf.urls.static import static

# API路由库
from rest_framework.routers import DefaultRouter
from rest_framework.documentation import include_docs_urls

# --- View ---
from blog.views import (
    IndexView, CategoryView, TagView, PostDetailView, SearchView, AuthorView,
)
from blog.rss import LatestPostFeed
from blog.sitemap import PostSitemap
from blog.apis import PostViewSet, CategoryViewSet
from config.views import LinkListView
from comment.views import CommentView
from .custom_site import custom_site  # 自定义站点（admin）

# xadmin.autodiscover()
mgadmin.autodiscover()
xversion.register_models()  # version模块自动注册需要版本控制的 Model

# API路由
router = DefaultRouter()
router.register(r'post', PostViewSet, basename='api-post')  # 相当于设置PostViewSet的URL为/api/post
router.register(r'category', CategoryViewSet, basename='api-category')  # 相当于设置CategoryViewSet的URL为/api/category

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('category/<int:category_id>/', CategoryView.as_view(), name='category-list'),
    path('tag/<int:tag_id>/', TagView.as_view(), name='tag-list'),
    path('search/', SearchView.as_view(), name='search'),
    path('author/<owner_id>', AuthorView.as_view(), name='author'),
    path('post/<int:post_id>.html', PostDetailView.as_view(), name='post-detail'),
    path('rss/', LatestPostFeed(), name='rss'),
    # 缓存有三个参数，第一个表示缓存时间（这里缓存20分钟有效），cache="default"默认即为使用默认缓存，key_prefix表示缓存秘钥前缀字符串，本质是返回装饰器
    path('sitemap.xml', cache_page(60 * 20, key_prefix='sitemap_cache_')(sitemap_views.sitemap), {'sitemaps': {'posts': PostSitemap}}),
    path('comment/', CommentView.as_view(), name='comment'),
    path('links/', LinkListView.as_view(), name='links'),
    path('super_admin/', admin.site.urls, name='super-admin'),
    path('admin/', custom_site.urls, name='admin'),
    # path('xadmin/', xadmin.site.urls, name='xadmin'),
    path('mgadmin/', mgadmin.site.urls, name='mgadmin'),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('api/', include(router.urls)),
    path('api/docs/', include_docs_urls(title='lukeblog apis')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# 如果开启Debug模式，则增加Django-Debug-Toolbar的URL配置
if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

lukeblog/comment/models.py
from django.db import models

from blog.models import Post


class Comment(models.Model):
    STATUS_UNAUDITED = 2  # 未审核
    STATUS_NORMAL = 1
    STATUS_DELETE = 0
    STATUS_ITEMS = (
        (STATUS_UNAUDITED, '未审核'),
        (STATUS_NORMAL, '正常'),
        (STATUS_DELETE, '删除'),
    )

    target = models.CharField(max_length=100, verbose_name="评论目标")
    content = models.CharField(max_length=2000, verbose_name="内容")
    nickname = models.CharField(max_length=50, verbose_name="昵称")
    website = models.URLField(verbose_name="网站")
    email = models.EmailField(verbose_name="邮箱")
    status = models.PositiveIntegerField(default=STATUS_UNAUDITED, choices=STATUS_ITEMS, verbose_name="状态")
    created_time = models.DateTimeField(auto_now_add=True, verbose_name="创建时间")

    @classmethod
    def get_by_target(cls, target):
        return cls.objects.filter(target=target, status=cls.STATUS_NORMAL)

    class Meta:
        verbose_name = verbose_name_plural = '评论'

lukeblog/comment/forms.py
from django import forms

from .models import Comment


class CommentForm(forms.ModelForm):
    # 注：这里只要提供需要用户填写的部分。target这种由系统指定的字段，在html添加隐藏input，然后View中处理POST来的数据，保存至表单数据库内。
    nickname = forms.CharField(
        label='昵称',
        max_length=50,
        widget=forms.widgets.Input(
            attrs={'class': 'form-control', 'style': "width: 60%;"}
        )
    )
    email = forms.CharField(
        label='E-mail',
        max_length=50,
        widget=forms.widgets.EmailInput(
            attrs={'class': 'form-control', 'style': "width: 60%;"}
        )
    )
    website = forms.CharField(
        label='网站',
        max_length=100,
        widget=forms.widgets.URLInput(
            attrs={'class': 'form-control', 'style': "width:60%;"}
        )
    )
    content = forms.CharField(
        label='内容',
        max_length=500,
        widget=forms.widgets.Textarea(
            attrs={'rows': 6, 'cols': 60, 'class': 'form-control'}
        )
    )

    def clean_content(self):
        content = self.cleaned_data.get('content')
        if len(content) < 5:
            raise forms.ValidationError('长度过短哦！')
        return content

    class Meta:
        model = Comment
        fields = ['nickname', 'email', 'website', 'content']

lukeblog/comment/views.py
from django.shortcuts import redirect  # 重定向模块
from django.views.generic import TemplateView

from .forms import CommentForm


class CommentView(TemplateView):
    """ 评论表单的action功能页面 """
    http_method_names = ['post']  # 此View只处理POST请求
    template_name = 'comment/result.html'  # 返回结果页的模板

    def post(self, request, *args, **kwargs):
        """ 重写POST请求逻辑 """
        comment_form = CommentForm(request.POST)  # 根据forms.py中定义的用户输入表单，取出POST提交表单中用户输入的数据
        target = request.POST.get('target')  # 取出表单中隐藏的target值

        if comment_form.is_valid():  # 如果数据有效
            instance = comment_form.save(commit=False)  # 保存表单为一个实例，但不提交到数据库，默认为True
            instance.target = target  # 添加上述表单实例属性target（值为之前取回的来自页面POST的值）
            instance.save()  # 保存表单并提交到数据库
            succeed = True
            # return redirect(target)  # 重定向到表单提交页面，如果没有这句，将往下执行，返回提交成功的提示
        else:
            succeed = False

        context = {
            'succeed': succeed,
            'form': comment_form,
            'target': target,
        }
        return self.render_to_response(context)

lukeblog/lukeblog/themes/bootstrap/templates/comment/block.html
<hr/>
<div class="comment">
    <form class="form-group" action="/comment/" method="POST">
        {% csrf_token %}
        <input name="target" type="hidden" value="{{ target }}"/>
        {{ comment_form }}
        <input type="submit" value="发表评论"/>
    </form>
    <!-- 评论列表 -->
    <ul class="list-group">
        {% for comment in comment_list %}
            <li class="list-group-item">
                <div class="nickname">
                    <a href="{{ comment.website }}" target="_blank">{{ comment.nickname }}</a>
                    <span>{{ comment.created_time }}</span>
                </div>
                <div class="comment-content">
                    {{ comment.content }}
                </div>
            </li>
        {% endfor %}
    </ul>
</div>

lukeblog/lukeblog/themes/bootstrap/templates/comment/result.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>评论结果页</title>
    <style>
        body {text-align: center;}
        .result {
            text-align: center;
            width: 40%;
            margin: auto;
        }
        .errorlist {color: red;}
        ul li {list-style-type: None;}
    </style>
</head>
<body>
    <div class="result">
        {% if succeed %}
            评论成功，请耐心等待审核哦！
            <a href="{{ target }}">返回</a>
        {% else %}
            <ul class="errorlist">
                {% for field, message in form.errors.items %}
                    <li>{{ message }}</li>
                {% endfor %}
            </ul>
            <a href="javascript:window.history.back();">返回</a>
        {% endif %}
    </div>
</body>
</html>